#!/bin/bash

TIMESTAMP=$(date +%Y-%m-%d_%H-%M)

sudo btrfs subvolume snapshot -r /@ /.snapshots/root-$TIMESTAMP
sudo btrfs subvolume snapshot -r /@home /.snapshots/home-$TIMESTAMP
sudo btrfs subvolume snapshot -r /@var /.snapshots/var-$TIMESTAMP
sudo btrfs subvolume snapshot -r /@var_tmp /.snapshots/var_tmp-$TIMESTAMP
sudo btrfs subvolume snapshot -r /@var_lib_pacman /.snapshots/var_lib_pacman-$TIMESTAMP

echo "✅ Snapshots created at $TIMESTAMP"
